name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm dosfstools mtools genisoimage wget unzip

      - name: Download and Extract FreeDOS files
        run: |
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.4/FD14-LiveCD.zip
          unzip FD14-LiveCD.zip
          mkdir dos_files
          # FreeDOS 1.4のISOから必要なファイルを抽出
          7z x FD14-LiveCD.iso
          cp FREEDOS/KERNEL.SYS dos_files/
          cp FREEDOS/COMMAND.COM dos_files/
          cp FREEDOS/FDCONFIG.SYS dos_files/
          cp FREEDOS/AUTOEXEC.BAT dos_files/
          # 不要なファイルを削除
          rm -rf FREEDOS
          rm FD14-LiveCD.iso
          rm FD14-LiveCD.zip

      - name: Create PC-98 IPL and system
        run: |
          # Create README
          cat > README.txt << 'EOF'
          XROGER DOS HDDイメージ
          作成日時: 2025-07-18 15:48:44 (UTC)
          作成者: Emon2358

          【注意事項】
          ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
          ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
            イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

          【免責事項】
          ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
          ・すべて自身の責任においてご利用ください。
          ・問い合わせも不可とさせていただきます。

          EOF

          # Create improved IPL for FreeDOS(98)
          cat > ipl.asm << 'EOF'
          [BITS 16]
          [ORG 0x0]
          
          ; BPB (BIOS Parameter Block)
          jmp short boot_start
          nop
          
          OEMLabel:           db "XROGDOS "  ; 8 bytes
          BytesPerSector:     dw 512
          SectorsPerCluster:  db 1
          ReservedSectors:    dw 1
          NumberOfFATs:       db 2
          RootDirEntries:     dw 224
          TotalSectors:       dw 2880        ; 1.44MB
          MediaDescriptor:    db 0xF0        ; 3.5" 1.44MB floppy
          SectorsPerFAT:      dw 9
          SectorsPerTrack:    dw 18
          NumberOfHeads:      dw 2
          HiddenSectors:      dd 0
          TotalSectorsBig:    dd 0
          DriveNumber:        db 0
          Reserved:           db 0
          ExtBootSignature:   db 0x29
          VolumeID:          dd 0x12345678
          VolumeLabel:        db "XROGER-DOS "  ; 11 bytes
          FileSysType:        db "FAT12   "    ; 8 bytes

          boot_start:
              ; PC-98向けの初期化
              cli
              xor ax, ax
              mov ss, ax
              mov sp, 0x7C00
              mov ds, ax
              mov es, ax
              sti

              ; PC-98 BIOS用の画面初期化
              mov ah, 0x00           ; テキストモード設定
              mov al, 0x00
              int 0x18

              ; ディスクリセット
              mov ah, 0x00
              mov dl, 0x80          ; HDDを指定
              int 0x13

              ; ルートディレクトリの読み込み
              mov ax, 19            ; ルートディレクトリの開始セクタ
              mov bx, 0x8000        ; バッファアドレス
              call read_sectors

              ; KERNEL.SYSの検索
              mov cx, 224           ; ルートディレクトリエントリ数
              mov di, 0x8000        ; 検索開始アドレス
          find_kernel:
              push cx
              mov cx, 11            ; ファイル名の長さ
              mov si, kernel_name
              push di
              repe cmpsb
              pop di
              je kernel_found
              pop cx
              add di, 32            ; 次のディレクトリエントリ
              loop find_kernel
              jmp boot_error

          kernel_found:
              ; KERNEL.SYSの読み込みと実行
              mov ax, [di + 26]     ; 最初のクラスタ番号
              mov bx, 0x1000        ; 読み込み先アドレス
              call load_kernel
              
              ; KERNEL.SYSに制御を移す
              jmp 0x0000:0x1000

          read_sectors:
              push ax
              push cx
              push dx
              
              mov cx, 1             ; 1セクタ読み込み
              xor dx, dx            ; ヘッド0, ドライブ0
              int 0x13
              
              pop dx
              pop cx
              pop ax
              ret

          load_kernel:
              ; カーネル読み込み処理
              push ax
              push bx
              push cx
              
              mov cx, 32            ; 読み込むセクタ数（仮の値）
              int 0x13
              
              pop cx
              pop bx
              pop ax
              ret

          boot_error:
              ; エラーメッセージ表示
              mov si, error_msg
              call print_string
              jmp $

          print_string:
              lodsb
              or al, al
              jz .done
              mov ah, 0x0A          ; PC-98 BIOS文字出力
              int 0x18
              jmp print_string
          .done:
              ret

          kernel_name:    db "KERNEL  SYS"
          error_msg:      db "Error: KERNEL.SYS not found", 13, 10, 0

          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          
          # Assemble IPL
          nasm -f bin -o ipl.bin ipl.asm

      - name: Create HDI image
        run: |
          # Create blank 1.44MB HDI
          dd if=/dev/zero of=xroger.hdi bs=1024 count=1440
          
          # Write IPL
          dd if=ipl.bin of=xroger.hdi conv=notrunc
          
          # Format as FAT12
          mkfs.fat -F 12 -n "XROGER-DOS" xroger.hdi
          
          # Create temporary mount point
          mkdir -p tmp_mount
          
          # Mount the image
          sudo mount -o loop xroger.hdi tmp_mount
          
          # Copy system files
          sudo cp dos_files/KERNEL.SYS tmp_mount/
          sudo cp dos_files/COMMAND.COM tmp_mount/
          sudo cp dos_files/FDCONFIG.SYS tmp_mount/CONFIG.SYS
          sudo cp README.txt tmp_mount/
          
          # Create/modify configuration files
          echo "LASTDRIVE=Z" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "FILES=40" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "BUFFERS=40" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DOS=HIGH,UMB" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DEVICE=HIMEM.SYS" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DEVICEHIGH=EMM386.EXE NOEMS" | sudo tee -a tmp_mount/CONFIG.SYS
          
          echo "@ECHO OFF" | sudo tee tmp_mount/AUTOEXEC.BAT
          echo "PATH C:\;C:\DOS" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "SET TEMP=C:\TEMP" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "PROMPT $P$G" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "CLS" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "ECHO Welcome to XROGER-DOS!" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          
          # Unmount
          sudo umount tmp_mount
          rm -rf tmp_mount

      - name: Upload HDI file
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: |
            xroger.hdi
            README.txt
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: |
            xroger.hdi
            README.txt
          name: Xroger DOS Release
          body: |
            XROGER DOS HDDイメージ
            作成日時: 2025-07-18 15:48:44 (UTC)
            作成者: Emon2358

            【注意事項】
            ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
            ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
              イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

            【免責事項】
            ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
            ・すべて自身の責任においてご利用ください。
            ・問い合わせも不可とさせていただきます。
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
