name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm dosfstools mtools genisoimage wget unzip p7zip-full qemu-utils

      - name: Download and Convert FreeDOS
        run: |
          # Download FreeDOS
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.4/FD14-LiveCD.zip
          
          # Extract ISO
          unzip FD14-LiveCD.zip
          
          # Debug: List contents
          echo "Listing contents of current directory:"
          ls -la
          
          # Mount ISO and show contents
          mkdir -p iso_mount
          sudo mount -o loop FD14LIVE.iso iso_mount
          
          echo "Listing contents of ISO mount:"
          ls -laR iso_mount/
          
          # Create HDI
          qemu-img create -f raw xroger.hdi 1474560
          
          # Format HDI
          mkfs.fat -F 12 -n "XROGER-DOS" xroger.hdi
          
          # Mount HDI
          mkdir -p hdi_mount
          sudo mount -o loop xroger.hdi hdi_mount
          
          # Create DOS directory structure
          sudo mkdir -p hdi_mount/DOS
          
          # Copy FreeDOS system files (adjust paths based on ISO structure)
          echo "Copying system files..."
          sudo find iso_mount -iname "kernel.sys" -exec cp {} hdi_mount/ \;
          sudo find iso_mount -iname "command.com" -exec cp {} hdi_mount/ \;
          sudo find iso_mount -iname "himem.sys" -exec cp {} hdi_mount/DOS/ \;
          sudo find iso_mount -iname "emm386.exe" -exec cp {} hdi_mount/DOS/ \;
          
          # List copied files
          echo "Contents of HDI mount:"
          ls -laR hdi_mount/
          
          # Create README
          cat > README.txt << EOF
          XROGER DOS HDDイメージ
          作成日時: 2025-07-18 16:26:15 (UTC)
          作成者: Emon2358

          【注意事項】
          ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
          ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
            イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

          【免責事項】
          ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
          ・すべて自身の責任においてご利用ください。
          ・問い合わせも不可とさせていただきます。
          EOF
          
          sudo cp README.txt hdi_mount/
          
          # Create configuration files
          echo "Creating CONFIG.SYS..."
          cat > config.sys << EOF
          LASTDRIVE=Z
          FILES=40
          BUFFERS=40
          DOS=HIGH,UMB
          DEVICE=DOS\HIMEM.SYS
          DEVICEHIGH=DOS\EMM386.EXE NOEMS
          SHELL=COMMAND.COM /P /E:512
          EOF
          sudo cp config.sys hdi_mount/CONFIG.SYS
          
          echo "Creating AUTOEXEC.BAT..."
          cat > autoexec.bat << EOF
          @ECHO OFF
          PROMPT \$P\$G
          PATH C:\;C:\DOS
          SET TEMP=C:\TEMP
          MKDIR C:\TEMP
          CLS
          ECHO Welcome to XROGER-DOS!
          EOF
          sudo cp autoexec.bat hdi_mount/AUTOEXEC.BAT
          
          # Create IPL
          cat > ipl.asm << 'EOF'
          [BITS 16]
          [ORG 0x0]
          
          ; BPB (BIOS Parameter Block)
          jmp short boot_start
          nop
          
          OEMLabel:           db "XROGDOS "  ; 8 bytes
          BytesPerSector:     dw 512
          SectorsPerCluster:  db 1
          ReservedSectors:    dw 1
          NumberOfFATs:       db 2
          RootDirEntries:     dw 224
          TotalSectors:       dw 2880        ; 1.44MB
          MediaDescriptor:    db 0xF0        ; 3.5" 1.44MB floppy
          SectorsPerFAT:      dw 9
          SectorsPerTrack:    dw 18
          NumberOfHeads:      dw 2
          HiddenSectors:      dd 0
          TotalSectorsBig:    dd 0
          DriveNumber:        db 0x80        ; ハードディスクとして認識
          Reserved:           db 0
          ExtBootSignature:   db 0x29
          VolumeID:          dd 0x12345678
          VolumeLabel:        db "XROGER-DOS "  ; 11 bytes
          FileSysType:        db "FAT12   "    ; 8 bytes

          boot_start:
              ; PC-98向けの初期化
              cli
              xor ax, ax
              mov ss, ax
              mov sp, 0x7C00
              mov ds, ax
              mov es, ax
              sti

              ; PC-98 BIOS用の画面初期化
              mov ah, 0x00           ; テキストモード設定
              mov al, 0x00
              int 0x18

              ; Reset disk system
              xor ax, ax
              int 0x13
              jc error

              ; Load KERNEL.SYS
              mov ax, 0x1000        ; Load address
              mov es, ax
              xor bx, bx
              
              mov ax, 0x0201        ; Read one sector
              mov cx, 0x0002        ; Track 0, Sector 2
              xor dh, dh           ; Head 0
              mov dl, 0x80          ; Drive 0x80 (HDD)
              int 0x13
              jc error

              ; Jump to kernel
              jmp 0x1000:0x0000

          error:
              mov si, error_msg
              call print_string
              jmp $

          print_string:
              lodsb
              or al, al
              jz .done
              mov ah, 0x0A          ; PC-98 BIOS文字出力
              int 0x18
              jmp print_string
          .done:
              ret

          error_msg:      db "Boot Error: System halted", 13, 10, 0

          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          
          # Compile IPL
          nasm -f bin -o ipl.bin ipl.asm
          
          # Write IPL to HDI
          dd if=ipl.bin of=xroger.hdi conv=notrunc bs=512 count=1
          
          # Unmount everything
          sudo umount iso_mount || true
          sudo umount hdi_mount || true
          
          # Cleanup
          rm -rf iso_mount hdi_mount
          rm -f FD14LIVE.iso FD14BOOT.img
          rm -f ipl.bin config.sys autoexec.bat
          
          # Debug info
          echo "Final contents:"
          ls -la
          file xroger.hdi

      - name: Upload HDI file
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: |
            xroger.hdi
            README.txt
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: |
            xroger.hdi
            README.txt
          name: Xroger DOS Release
          body: |
            XROGER DOS HDDイメージ
            作成日時: 2025-07-18 16:26:15 (UTC)
            作成者: Emon2358

            【注意事項】
            ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
            ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
              イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

            【免責事項】
            ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
            ・すべて自身の責任においてご利用ください。
            ・問い合わせも不可とさせていただきます。
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
