name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm dosfstools

      - name: Create PC-98 bootloader
        run: |
          cat > boot.asm << 'EOF'
          [BITS 16]
          [ORG 0x0100]
          
              jmp short start
            nop
            
          ; BPB (BIOS Parameter Block)
          OEMLabel        db "XROGERDOS"  ; 8 bytes
          BytesPerSector  dw 512
          SecPerCluster   db 1
          ReservedSectors dw 1
          NumFATs         db 2
          RootDirEntries  dw 224
          TotalSectors    dw 2880         ; 1.44 MB
          MediaType       db 0xF0         ; 3.5" 1.44M
          SectorsPerFAT   dw 9
          SectorsPerTrack dw 18
          NumHeads        dw 2
          HiddenSectors   dd 0
          LargeSectors    dd 0
          DriveNumber     db 0
          Reserved        db 0
          ExtBootSign     db 0x29
          SerialNumber    dd 0xDEADBEEF
          VolumeLabel     db "XROGER DOS "  ; 11 bytes
          FileSystem      db "FAT12   "    ; 8 bytes
          
          start:
              ; セットアップ
              cli
              mov ax, 0x07C0
              mov ds, ax
              mov es, ax
              mov ax, 0x8000
              mov ss, ax
              mov sp, 0xFFFE
              sti
              
              ; 画面クリア
              mov ax, 0x0600
              mov bh, 0x07
              mov cx, 0x0000
              mov dx, 0x184F
              int 0x10
              
              ; メッセージ表示
              mov si, welcome_msg
              call print_string
              
              jmp $
          
          print_string:
              lodsb
              or al, al
              jz .done
              mov ah, 0x0E
              int 0x10
              jmp print_string
          .done:
              ret
          
          welcome_msg:
              db 'Welcome to Xroger DOS v1.0', 13, 10
              db 'A custom DOS for PC-98', 13, 10
              db 'Created: 2025-07-18', 13, 10, 0
          
          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          
          nasm -f bin boot.asm -o boot.bin

      - name: Create HDI image
        run: |
          # Create initial disk image (1.44MB)
          dd if=/dev/zero of=disk.img bs=512 count=2880
          
          # Write bootloader
          dd if=boot.bin of=disk.img conv=notrunc
          
          # Create system files
          echo -e "XRoger System File" > system.dat
          echo -e "@ECHO OFF\nECHO Welcome to XRoger DOS" > autoexec.dat
          echo -e "DEVICE=XROGER.SYS" > config.dat
          
          # Calculate positions and write system files
          # First data sector starts after boot sector, FATs, and root directory
          # Root directory starts at sector 19 (1 boot + 18 FAT)
          dd if=system.dat of=disk.img bs=512 seek=33 conv=notrunc
          dd if=autoexec.dat of=disk.img bs=512 seek=34 conv=notrunc
          dd if=config.dat of=disk.img bs=512 seek=35 conv=notrunc
          
          # Create HDI file
          mv disk.img xroger.hdi

      - name: Upload HDI file
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: xroger.hdi
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: xroger.hdi
          name: Xroger DOS Release
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
