name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm dosfstools mtools genisoimage wget unzip p7zip-full

      - name: Download and Extract FreeDOS files
        run: |
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.4/FD14-LiveCD.zip
          mkdir dos_files
          # ZIPファイルから直接必要なファイルを抽出
          7z x FD14-LiveCD.zip -o./temp_freedos
          cd temp_freedos
          # LiveCDのISOファイルを見つけて展開
          ISO_FILE=$(find . -name "*.iso" -type f)
          7z x "$ISO_FILE" -o./iso_contents
          # 必要なファイルをコピー
          find ./iso_contents -iname "KERNEL.SYS" -exec cp {} ../dos_files/ \;
          find ./iso_contents -iname "COMMAND.COM" -exec cp {} ../dos_files/ \;
          find ./iso_contents -iname "HIMEM.SYS" -exec cp {} ../dos_files/ \;
          find ./iso_contents -iname "EMM386.EXE" -exec cp {} ../dos_files/ \;
          cd ..
          # 一時ファイルを削除
          rm -rf temp_freedos
          rm FD14-LiveCD.zip

      - name: Create PC-98 IPL and system
        run: |
          # Create README
          cat > README.txt << 'EOF'
          XROGER DOS HDDイメージ
          作成日時: 2025-07-18 15:52:41 (UTC)
          作成者: Emon2358

          【注意事項】
          ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
          ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
            イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

          【免責事項】
          ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
          ・すべて自身の責任においてご利用ください。
          ・問い合わせも不可とさせていただきます。

          EOF

          # Create improved IPL for FreeDOS(98)
          cat > ipl.asm << 'EOF'
          [BITS 16]
          [ORG 0x0]
          
          ; BPB (BIOS Parameter Block)
          jmp short boot_start
          nop
          
          OEMLabel:           db "XROGDOS "  ; 8 bytes
          BytesPerSector:     dw 512
          SectorsPerCluster:  db 1
          ReservedSectors:    dw 1
          NumberOfFATs:       db 2
          RootDirEntries:     dw 224
          TotalSectors:       dw 2880        ; 1.44MB
          MediaDescriptor:    db 0xF0        ; 3.5" 1.44MB floppy
          SectorsPerFAT:      dw 9
          SectorsPerTrack:    dw 18
          NumberOfHeads:      dw 2
          HiddenSectors:      dd 0
          TotalSectorsBig:    dd 0
          DriveNumber:        db 0x80        ; ハードディスクとして認識
          Reserved:           db 0
          ExtBootSignature:   db 0x29
          VolumeID:          dd 0x12345678
          VolumeLabel:        db "XROGER-DOS "  ; 11 bytes
          FileSysType:        db "FAT12   "    ; 8 bytes

          boot_start:
              ; PC-98向けの初期化
              cli
              xor ax, ax
              mov ss, ax
              mov sp, 0x7C00
              mov ds, ax
              mov es, ax
              sti

              ; PC-98 BIOS用の画面初期化
              mov ah, 0x00           ; テキストモード設定
              mov al, 0x00
              int 0x18

              ; ディスクリセット
              mov ah, 0x00
              mov dl, 0x80          ; HDDを指定
              int 0x13

              ; KERNEL.SYSをロード
              mov ax, 0x1000
              mov es, ax            ; ES:BX = 0x1000:0x0000
              xor bx, bx
              mov ax, 0x0201        ; AH=02 (read), AL=01 (1 sector)
              mov cx, 0x0002        ; CH=0 (cylinder), CL=2 (sector)
              xor dh, dh           ; DH=0 (head)
              mov dl, 0x80          ; DL=0x80 (first hard disk)
              int 0x13
              jc error

              ; KERNELにジャンプ
              jmp 0x1000:0x0000

          error:
              mov si, error_msg
              call print_string
              jmp $

          print_string:
              lodsb
              or al, al
              jz .done
              mov ah, 0x0A          ; PC-98 BIOS文字出力
              int 0x18
              jmp print_string
          .done:
              ret

          error_msg:      db "Error: Failed to load KERNEL.SYS", 13, 10, 0

          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          
          # Assemble IPL
          nasm -f bin -o ipl.bin ipl.asm

      - name: Create HDI image
        run: |
          # Create blank 1.44MB HDI
          dd if=/dev/zero of=xroger.hdi bs=1024 count=1440
          
          # Write IPL
          dd if=ipl.bin of=xroger.hdi conv=notrunc
          
          # Format as FAT12
          mkfs.fat -F 12 -n "XROGER-DOS" xroger.hdi
          
          # Create temporary mount point
          mkdir -p tmp_mount
          
          # Mount the image
          sudo mount -o loop xroger.hdi tmp_mount
          
          # Copy system files
          sudo cp dos_files/KERNEL.SYS tmp_mount/
          sudo cp dos_files/COMMAND.COM tmp_mount/
          sudo cp dos_files/HIMEM.SYS tmp_mount/
          sudo cp dos_files/EMM386.EXE tmp_mount/
          sudo cp README.txt tmp_mount/
          
          # Create configuration files
          echo "LASTDRIVE=Z" | sudo tee tmp_mount/CONFIG.SYS
          echo "FILES=40" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "BUFFERS=40" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DOS=HIGH,UMB" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DEVICE=HIMEM.SYS" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "DEVICEHIGH=EMM386.EXE NOEMS" | sudo tee -a tmp_mount/CONFIG.SYS
          echo "SHELL=C:\COMMAND.COM /P /E:512" | sudo tee -a tmp_mount/CONFIG.SYS
          
          echo "@ECHO OFF" | sudo tee tmp_mount/AUTOEXEC.BAT
          echo "PROMPT $P$G" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "PATH C:\;C:\DOS" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "SET TEMP=C:\TEMP" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "MKDIR C:\TEMP" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "CLS" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          echo "ECHO Welcome to XROGER-DOS!" | sudo tee -a tmp_mount/AUTOEXEC.BAT
          
          # Unmount
          sudo umount tmp_mount
          rm -rf tmp_mount

      - name: Upload HDI file
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: |
            xroger.hdi
            README.txt
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: |
            xroger.hdi
            README.txt
          name: Xroger DOS Release
          body: |
            XROGER DOS HDDイメージ
            作成日時: 2025-07-18 15:52:41 (UTC)
            作成者: Emon2358

            【注意事項】
            ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
            ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
              イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

            【免責事項】
            ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
            ・すべて自身の責任においてご利用ください。
            ・問い合わせも不可とさせていただきます。
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
