name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm \
            dosfstools \
            mtools \
            genisoimage \
            wget \
            unzip \
            p7zip-full \
            qemu-utils \
            dosbox-x

      - name: Download FreeDOS LiveCD
        run: |
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.4/FD14-LiveCD.zip
          unzip FD14-LiveCD.zip

      - name: Assemble IPL (boot sector)
        run: |
          cat > ipl.asm << 'EOF'
          [BITS 16]
          [ORG 0x0]
          jmp short boot_start
          nop
          ; --- (rest of your IPL source, unchanged) ---
          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          nasm -f bin -o ipl.bin ipl.asm

      - name: Create PC‑98 HDD image & format
        run: |
          # 1) Create .hdi with PC‑98 header
          dosbox-x -c "createhd -hdimage xroger.hdi \
                                  -size 1474560 \
                                  -interface ide \
                                  -geometry 80,2,18" \
                    -c "quit"
          # 2) Format as FAT12 using mtools (matching 80×2×18 geometry)
          echo "drive x: file=\"$(pwd)/xroger.hdi\" offset=0" > ~/.mtoolsrc
          mformat -i xroger.hdi -f 1440 -T 18 -H 2 -S 512 -n XROGER-DOS ::

          # 3) Install custom IPL into sector #1 (skip DOSBox‑X header)
          dd if=ipl.bin of=xroger.hdi conv=notrunc bs=512 seek=1 count=1

      - name: Mount, copy FreeDOS files, and finalize
        run: |
          # Mount the HDD image at offset (skip 512‑byte DOSBox‑X header)
          mkdir -p hdi_mount
          sudo mount -o loop,offset=512 xroger.hdi hdi_mount

          # Mount the FreeDOS LiveCD ISO
          mkdir -p iso_mount
          sudo mount -o loop FD14LIVE.iso iso_mount

          # Copy root files into the image
          echo "Copying system files to HDI root..."
          for file in KERNEL.SYS COMMAND.COM FDCONFIG.SYS IO.SYS MSDOS.SYS; do
            sudo find iso_mount -iname "$file" -exec cp {} hdi_mount/ \; || true
          done

          # Copy additional DOS drivers/utilities
          sudo mkdir -p hdi_mount/DOS
          for file in HIMEM.SYS EMM386.EXE FDOS.SYS; do
            sudo find iso_mount -iname "$file" -exec cp {} hdi_mount/DOS/ \; || true
          done

          # Create minimal CONFIG.SYS & AUTOEXEC.BAT
          cat > config.sys << EOF
          DEVICE=DOS\HIMEM.SYS
          DOS=HIGH
          FILES=40
          BUFFERS=40
          SHELL=COMMAND.COM /P /E:512
          EOF
          sudo cp config.sys hdi_mount/CONFIG.SYS

          cat > autoexec.bat << EOF
          @ECHO OFF
          SET PATH=C:\;C:\DOS
          PROMPT $P$G
          EOF
          sudo cp autoexec.bat hdi_mount/AUTOEXEC.BAT

          # Create README
          cat > README.txt << EOF
          XROGER DOS HDDイメージ
          作成日時: 2025-07-18 16:31:17 (UTC)
          作成者: Emon2358

          【注意事項】
          ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
          ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
            イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

          【免責事項】
          ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
          ・すべて自身の責任においてご利用ください。
          ・問い合わせも不可とさせていただきます。
          EOF
          sudo cp README.txt hdi_mount/

          # Unmount everything
          sudo umount iso_mount
          sudo umount hdi_mount

          # Cleanup intermediates
          rm -rf iso_mount hdi_mount FD14LIVE.iso ipl.asm config.sys autoexec.bat

          # Verify
          ls -l xroger.hdi
          file xroger.hdi

      - name: Upload HDI & README
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: |
            xroger.hdi
            README.txt

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: |
            xroger.hdi
            README.txt
          name: Xroger DOS Release
          body_path: README.txt
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

