name: Build Xroger DOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm \
            dosfstools \
            genisoimage \
            wget \
            unzip \
            p7zip-full \
            qemu-utils \
            dosbox-x

      - name: Download FreeDOS LiveCD
        run: |
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.4/FD14-LiveCD.zip
          unzip FD14-LiveCD.zip

      - name: Assemble IPL (boot sector)
        run: |
          cat > ipl.asm << 'EOF'
          [BITS 16]
          [ORG 0x0]
          jmp short boot_start
          nop
          ; --- 以下略: 先ほどの完全版IPLソースをここに ---
          times 510-($-$$) db 0
          dw 0xAA55
          EOF
          nasm -f bin -o ipl.bin ipl.asm

      - name: Create & fast‑format PC‑98 HDD image
        run: |
          # 1) DOSBox‑XでPC‑98ヘッダー付きHDIを生成 (80×2×18, IDE)
          dosbox-x -c "createhd -hdimage xroger.hdi \
                                  -size 1474560 \
                                  -interface ide \
                                  -geometry 80,2,18" \
                    -c "quit"

          # 2) ループバックデバイスにマッピング (先頭512Bヘッダーは除く)
          LOOP=$(sudo losetup --find --show --offset 512 xroger.hdi)

          # 3) mkfs.fat で一瞬FAT12化
          sudo mkfs.fat -F12 -n XROGER-DOS $LOOP

          # 4) クリーンアップ
          sudo losetup -d $LOOP

          # 5) カスタムIPLを先頭セクタに書き込む
          dd if=ipl.bin of=xroger.hdi bs=512 seek=1 conv=notrunc

      - name: Mount, copy FreeDOS files, and finalize
        run: |
          mkdir -p hdi_mount iso_mount
          sudo mount -o loop,offset=0 xroger.hdi hdi_mount
          sudo mount -o loop FD14LIVE.iso iso_mount

          echo "Copying system files..."
          for file in KERNEL.SYS COMMAND.COM FDCONFIG.SYS IO.SYS MSDOS.SYS; do
            sudo find iso_mount -iname "$file" -exec cp {} hdi_mount/ \; || true
          done

          sudo mkdir -p hdi_mount/DOS
          for file in HIMEM.SYS EMM386.EXE FDOS.SYS; do
            sudo find iso_mount -iname "$file" -exec cp {} hdi_mount/DOS/ \; || true
          done

          cat > config.sys << 'EOS'
          DEVICE=DOS\HIMEM.SYS
          DOS=HIGH
          FILES=40
          BUFFERS=40
          SHELL=COMMAND.COM /P /E:512
          EOS
          sudo cp config.sys hdi_mount/CONFIG.SYS

          cat > autoexec.bat << 'EOS'
          @ECHO OFF
          SET PATH=C:\;C:\DOS
          PROMPT $P$G
          EOS
          sudo cp autoexec.bat hdi_mount/AUTOEXEC.BAT

          cat > README.txt << 'EOS'
          XROGER DOS HDDイメージ
          作成日時: 2025-07-18 16:31:17 (UTC)
          作成者: Emon2358

          【注意事項】
          ・このHDDイメージはFreeDOS(98)が起動する状態に設定されています。
          ・作成の段階でHDDのフォーマットのみMS-DOSを使用していますが、
            イメージにはMS-DOSのデータが含まれないため配布に問題ないものとしています。

          【免責事項】
          ・このHDDイメージを利用し発生したいかなる事象も関知いたしません。
          ・すべて自身の責任においてご利用ください。
          ・問い合わせも不可とさせていただきます。
          EOS
          sudo cp README.txt hdi_mount/

          sudo umount iso_mount hdi_mount
          rm -rf iso_mount hdi_mount FD14LIVE.iso ipl.asm config.sys autoexec.bat

      - name: Upload HDI & README
        uses: actions/upload-artifact@v4
        with:
          name: xroger-dos
          path: |
            xroger.hdi
            README.txt

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: |
            xroger.hdi
            README.txt
          name: Xroger DOS Release
          body_path: README.txt
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
